"""Init

Revision ID: fb66ff540989
Revises: 
Create Date: 2026-01-04 15:41:52.518947

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'fb66ff540989'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_metadata_filename'))

    op.drop_table('document_metadata')
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_postings_url'))

    op.drop_table('job_postings')
    with op.batch_alter_table('llm_configurations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_configurations_provider'))

    op.drop_table('llm_configurations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_configurations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('model_name', sa.VARCHAR(), nullable=False),
    sa.Column('api_key', sa.VARCHAR(), nullable=True),
    sa.Column('base_url', sa.VARCHAR(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_configurations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_configurations_provider'), ['provider'], unique=False)

    op.create_table('job_postings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=True),
    sa.Column('full_content', sa.VARCHAR(), nullable=True),
    sa.Column('generated_metadata', sqlite.JSON(), nullable=True),
    sa.Column('extraction_status', sa.VARCHAR(length=10), nullable=False),
    sa.Column('status_updated', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_postings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_postings_url'), ['url'], unique=False)

    op.create_table('document_metadata',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(), nullable=False),
    sa.Column('file_type', sa.VARCHAR(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_metadata_filename'), ['filename'], unique=False)

    # ### end Alembic commands ###
